### PR TITLE
registerType & resetTypes new functions

### PR DESCRIPTION
**Pull request by damienleroux**
Here is the new functions registerType & resetTypes.

### CODE REVIEW

**Comment by gcanti** [comment]
Hi, thanks a lot!

Two observations:

1. I'd add a check in `registerType` to avoid registering a reserved type (contained in `SchemaType`). Something like

  ```js
  t.assert(!SchemaType.is(typeName), '[tcomb-json-schema] Reserved type ' + typeName);
  ```

2. why the `util.doesArrayContain` function? Isn't a simple `registerTypes.hasOwnProperty` lookup enough?

**Comment by damienleroux** [comment]
Very good your first observation!
Concerning the second one, I didn't know Object has a function hasOwnProperty, my bad

**Comment by damienleroux** [comment]
I modify the code and re-push

**Comment by gcanti** [comment]
Great! Can I merge now?

**Comment by damienleroux** [comment]
Yes for sure. Thx

**Pull request merged**
