### PR TITLE
Added support for key value enums.

### PR DESCRIPTION
**Pull request by johnraz**
Before this patch, only a list of string could be provided to the enum
attribute, leading to a list of options with the same name and value for
each entry of the list.

With this patch, you can still provide a list or if you want to gain
control over the name and value of the options, you can provide a
dictionnary whose key will become the name and value, well, the displayed value.

eg:

	{
	  "type": "object",
	  "properties": {
	    "number":      { "type": "number" },
	    "street_name": { "type": "string" },
	    "street_type": {
	      "type": "string",
	      "enum": ["Street", "Avenue", "Boulevard"]
	    }
	  }
	}
    OR
	{
	  "type": "object",
	  "properties": {
		"number":      { "type": "number" },
		"street_name": { "type": "string" },
		    "street_type": {
		      "type": "string",
		      "enum": {"street":"A Street", "avenue":"A nice avenue"}
		    }
	  }
	}

### CODE REVIEW

**Comment by gcanti** [comment]
Sorry for the possibly dumb question (I'm not an expert of json schema): is a dictionary a valid value for the `enum` key in the standard?

**Comment by johnraz** [comment]
Not sure to which standard you are referring, but I think (this)[http://json-schema.org/latest/json-schema-core.html#anchor7] is what you are looking for.

Anyway, nested dictionary is perfectly valid in a json objects offcourse ;-)

**Comment by gcanti** [comment]
Thanks for the link. I found this:

http://json-schema.org/latest/json-schema-validation.html#anchor76

> The value of this keyword MUST be an array. This array MUST have at least one element. Elements in the array MUST be unique. Elements in the array MAY be of any type, including null.

That's what I saw last time I checked (long time ago), hence my previous question

**Comment by johnraz** [comment]
You are totally right.

I don't really see how to go around this limitation of the standard...
I'm currently needing this for tcomb-form generation, as you probably guessed already.

I would argue that this is not "breaking" the standard as we are still compatible with the standard itself. We only make the project a bit less strict than it is now. Someone coming with a perfectly valid JSON schema would encounter no issue while someone in my position would be able to cover its use case.

**Comment by gcanti** [comment]
Ah.. I see. 

Sorry I don't want to be pedantic, your custom extension seems harmless, but speaking of standards I'm generally cautious.

What about to provide custom options? It would be awkward for you?

https://github.com/gcanti/tcomb-form/blob/master/GUIDE.md#custom-options

**Comment by johnraz** [comment]
Ha nice ! I totally overlooked the ability to specify the `options` via option ! 

Mmmm then I guess I can generate this on the side and still have the expected behavior.

I believe we can close this then - and I should RTFM more carefully next time ;-)

**Comment by gcanti** [comment]
> Mmmm then I guess I can generate this on the side and still have the expected behavior.

Yes. The additional benefit would be that your schemas, being standard, could play well with the tools of the json schema echosystem.

**Pull request closed without merging**
