### PR TITLE
closes #29 Date type

### LINKED ISSUE #29: Date pickers
We have some fields with `string` type but formatted as `date` or `date-time`. However, the returned output of the schema is `t.String` for those fields. Should we add support for `t.Date` when the format is `date` or similar?

If so, we're sending a PR tomorrow.

### PR DESCRIPTION
**Pull request by alvaromb**
Adds support for date types. JSON schema doesn't support dates and sends them as string with an added 'date', 'time' or 'date-time' format. This handles the case.

### CODE REVIEW

**Comment by gcanti** [comment]
Not sure I understand, let's say we have this schema

```json
{
  "type": "object",
  "properties": {
    "foo": {
      "type": "string",
      "format": "date"
    }
  }
}
```

and a suitable JSON

```json
{
  "foo": "2000-10-23" 
}
```

if the property `foo` gets the type `t.Date`, validation will always fail

**Comment by alvaromb** [comment]
Let me check.

**Comment by gcanti** [comment]
Could you please add a test? It would definitely help to understand what's going on

**Comment by alvaromb** [comment]
Sure!

**Comment by alvaromb** [comment]
@gcanti validation works in your example, because of this LOC in our intermediate library: https://github.com/APSL/tcomb-form-native-json-schema/blob/master/lib/values.js#L72

**Comment by alvaromb** [comment]
Basically, what our library does is parsing `options` and `value` from the JSON schema into a format the `Form` can understand.

**Comment by gcanti** [comment]
I see, but this library transforms a JSON Schema into a tcomb type which should be used to validate an imcoming JSON without assuming a deserialization phase (like yours)

Maybe we could change the signature of `registerFormat` to accept a type other than a predicate

```ts
registerFormat(format: string, predicate: (x: any) => boolean | Type): void
```

**Comment by alvaromb** [comment]
It could work but we still would need to return the `Type` in the `types` mapper if the format has a type instead a predicate, right?

**Comment by gcanti** [comment]
An early return before this line I guess https://github.com/gcanti/tcomb-json-schema/blob/0fb46e6434d3818b6b7da01baa9bd6b20e2f0cf6/index.js#L50

```js
if (t.isType(formats[s.format])) {
  return formats[s.format]
}
```

**Comment by alvaromb** [comment]
@gcanti AFAIK, that would return the format function only, not the `tcomb` type. I don't know if that would work, I think we would need to return a `type` or a `subtype`, right?

**Comment by alvaromb** [comment]
Sorry, I completely missed the point. That would work if we change the `registerFormat` to handle a `Type`.

**Comment by alvaromb** [comment]
Just uploaded code and tests, please give it a look and let me know what do you think.

Thanks!

**Comment by alvaromb** [comment]
New test is here https://github.com/gcanti/tcomb-json-schema/pull/30/files#diff-c1129c8b045390789fa8ff62f2c6b4a9R471

There are more changes due to prettier setup for `test.js`.

**Comment by alvaromb** [comment]
Have you managed to release the library, @gcanti?

**Comment by gcanti** [comment]
@alvaromb no, I was waiting for your placet. I'll publish a new version ASAP

**Comment by gcanti** [comment]
Released

**Pull request merged**
